version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: korean_rag_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    command: ./qdrant --config-path /qdrant/config/production.yaml 